services:
  toco-soap-db:
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toco_soap
      MYSQL_USER: toco
      MYSQL_PASSWORD: toco

  toco-soap:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
        - "8080:8080"
    depends_on:
      - toco-soap-db

